addr: :8719
log:
  location: log/space.log
  maxSize: 10       # megabytes
  maxBackups: 3
  maxAge: 28        # days
  mode: release
db:
  name: space
  addr: localhost:8003
  username: root
  password: 1010
gormlog: true
encrypt:
  jwt_secret: Rtx8BPKOEF2mB6mGVKENIPWYQS3JOEYijxR42qRgq0iBb5
