addr: :8765
route:
  back:
    base: "/api"
  front:
    dir: "dist"
    index: "dist/index.html"
log:
  location: log/space.log
  maxSize: 10       # megabytes
  maxBackups: 3
  maxAge: 28        # days
  mode: debug
db:
  name: space-dev
  addr: localhost:3306
  username: root
  password: 19730310
gormlog: true
encrypt:
  jwt_secret: Rtx8BPKOEF2mB6mGVKENIPWYQS3JOEYijxR42qRgq0iBb5
